[uwsgi]
module = app:app

virtualenv = /PATH/TO/venv
master = true
processes = 3

socket = /PATH/TO/webapp.sock
chmod-socket = 660
# USER should be the user running the backend
# GROUP should be the group which includes both this user and www-data (Nginx user)
chown-socket = USER:GROUP
vacuum = true

log-date = [%%Y:%%m:%%d %%H:%%M:%%S]
logformat = %(addr) - %(user) [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) "%(referer)" "%(uagent)"
logger = file:/PATH/TO/uwsgi.log

die-on-term = true
