#!/bin/ksh

# Copyright (C) 2013, Alexander L. Belikoff  ( http://belikoff.net )
# 
# This file is part of the project "Film Habibulina".
# 
# Film Habibulina is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Film Habibulina is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the project.  If not, see <http://www.gnu.org/licenses/>.


db=../data/habib.db
root_url="http://www.doslidy.kiev.ua/stories"

rm -f $db
sqlite3 $db < ../data/schema_sqlite.sql

for file in ../data/*.htm; do
    fname=$(basename $file)
    url=$(printf "%s/%s" $root_url $fname)
    print $fname
    ./les2db $db ../data/$file $url
done
