#!/usr/bin/env python
# -*- coding: utf-8 -*-

# parse HTML-formatted play into a DB


# Copyright (C) 2013, Alexander L. Belikoff  ( http://belikoff.net )
# 
# This file is part of the project "Film Habibulina".
# 
# Film Habibulina is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Film Habibulina is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the project.  If not, see <http://www.gnu.org/licenses/>.


import codecs
import unicodedata
import re
import os
import os.path
import logging
import sys
from optparse import OptionParser
import sqlite3


def replace_punct(x):
    punctutation_cats = set(['Pc', 'Pd', 'Ps', 'Pe', 'Pi', 'Pf', 'Po'])

    if unicodedata.category(x) in punctutation_cats:
        return ' '

    return x


def strip_punctuation(text):
    return ''.join(replace_punct(x) for x in text)


usage_string = """Usage:  %prog [options]  <db_file>  <play_file>  <url>

%prog takes the play file in HTML format, parses it and saves it
into a DB.
"""

prog = os.path.basename(sys.argv[0])
program_version = "1.0"
version_string = "%%prog  %s" % program_version

logging.basicConfig(format = prog + ": %(levelname)s: %(message)s")


# parse command-line options

parser = OptionParser(usage = usage_string,
                      version = version_string)
parser.add_option("-v", "--verbose", help = "verbose operation",
                  action = "store_true", dest = "verbose_mode")

(options, args) = parser.parse_args()

if options.verbose_mode:
    logging.getLogger().setLevel(logging.DEBUG)
else:
    logging.getLogger().setLevel(logging.INFO)

if len(args) != 3:
    parser.print_help()
    sys.exit()

db_file, in_file, url = args

conn = sqlite3.connect(db_file)
crs = conn.cursor()
num_speakers = 0
num_records = 0

with codecs.open(in_file, encoding = 'cp1251') as fin:
    title = None
    in_body = False
    play_id = None

    for line in fin:
        speaker = None

        # extract the title

        m = re.match(r'^\<h2\>(.*?)\.?(\<(\/h2|br)\>)\s*', line, re.IGNORECASE)

        if not title and m:
            title = m.group(1)
            crs.execute('INSERT INTO plays (title, url) VALUES (?, ?)',
                        (title, url))
            play_id = crs.lastrowid

            if options.verbose_mode:
                logging.debug("title: '%s', play ID: %d" % (title, play_id))
            
            continue

        # narrow to the body

        if not in_body and title and re.match('^\<\/?center\>', line,
                                              re.IGNORECASE):
            in_body = True

        if in_body and re.match('^\<hr', line):
            in_body = False

        if not in_body or re.match('^\s*$', line):
            continue


        # extract the speaker and the phrase (for future formatting)

        m = re.match(r'^\<b\>(.*?)\.?\<\/b\>\s*(\&nbsp\;)?(.*)', line)

        if m:
            speaker = m.group(1)
            phrase = m.group(3)
            num_speakers += 1
        else:
            phrase = line

        # clean up

        phrase = re.sub(r'\<\/?\S+?\>', '', phrase)
        phrase = re.sub(r'\&nbsp;', '', phrase)
        phrase = re.sub(r'\<font[^\>]*\>', '', phrase)
        phrase = re.sub(r'\s+$', '', phrase)

        if re.match('^\s*$', phrase) or phrase == u"Дійові особи":
            continue

        #if not speaker:
        #    print phrase.encode('utf8')
        
        # split into clean tokens

        tokens = set(strip_punctuation(phrase.lower()).split())
        tokens = [ t for t in tokens if (not re.match(r'^\s*$', t)
                                         and len(t) > 1) ]

        if len(tokens) < 2:
            continue

        if options.verbose_mode:
            if speaker:
                logging.debug("%s: %s" % (speaker, phrase))
            else:
                logging.debug("%s" % phrase)
        
        num_records += 1
        crs.execute("""
INSERT INTO quotes (play_id, speaker, phrase, tokens) VALUES (?,?,?,?)""",
                    (play_id, speaker, phrase, " ".join(tokens)))

conn.commit()
conn.close()
print("%s  %d  %d" % (os.path.basename(in_file), num_records, num_speakers))
sys.exit()
